services:
  - type: web
    name: zeroplate-ai
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_DB_NAME
        value: ZeroPlate_ai_MVP
